FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    curl bzip2 ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"

ENV PATH="/root/.local/share/solana/install/active_release/bin:${PATH}"

EXPOSE 8899 8900

CMD ["solana-test-validator", "--host", "0.0.0.0", "--log"]
