services:
  surfpool:
    image: docker.io/surfpool/surfpool
    container_name: surfpool-validator
    ports:
      - "8899:8899" # RPC
      - "8900:8900" # Gossip/WebSocket
      - "9900:9900" # Faucet
      - "3001:3001" # Prover
      - "8784:8784" # Photon Indexer
    volumes:
      - .:/work
    working_dir: /work
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8899/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["start", "--manifest-file-path", "/work/Surfpool.toml", "--no-tui", "--offline"]
