//! Groth16 heavy tests: golden vectors (py_ecc verified), tamper checks,
//! invariants, and stress.
//!
//! All "golden" constants were generated by scripts/gen_groth16_vectors.py
//! and cross-checked against py_ecc.bn128 pairing arithmetic.
//!
//! Setup (toxic waste, for test only):
//!   alpha_s=3, beta_s=5, gamma_s=7, delta_s=11
//!
//! Case 1: n_public=0, proof.A=15*G1, proof.B=G2, proof.C=INF
//! Case 2: n_public=1 (s=9), k0=13, k1=17, proof.A=1177*G1, proof.B=G2

const std     = @import("std");
const g1      = @import("g1.zig");
const g2      = @import("g2.zig");
const G1      = g1.G1;
const G2      = g2.G2;
const fp      = @import("fp.zig");
const groth16 = @import("groth16.zig");
const Proof      = groth16.Proof;
const VerifyingKey = groth16.VerifyingKey;

// ── Hex-decode helpers ────────────────────────────────────────────────────────

fn g1FromHex(comptime hex: *const [128:0]u8) G1 {
    var bytes: [64]u8 = undefined;
    _ = std.fmt.hexToBytes(&bytes, hex) catch unreachable;
    return G1.fromAffineBytes(&bytes);
}

fn g2FromHex(comptime hex: *const [256:0]u8) G2 {
    var bytes: [128]u8 = undefined;
    _ = std.fmt.hexToBytes(&bytes, hex) catch unreachable;
    return G2.fromAffineBytes(&bytes);
}

fn g1Inf() G1 { return G1.INFINITY; }

// ── Shared VK constants (same across Case 1 and Case 2) ──────────────────────

const ALPHA = "0769bf9ac56bea3ff40232bcb1b6bd159315d84715b8e679f2d355961915abf02ab799bee0489429554fdb7c8d086475319e63b40b9c5b57cdf1ff3dd9fe2261";
const BETA  = "0a09ccf561b55fd99d1c1208dee1162457b57ac5af3759d50671e510e428b2a12e539c423b302d13f4e5773c603948eaf5db5df8ae8a9a9113708390a06410d819b763513924a736e4eebd0d78c91c1bc1d657fee4214057d21414011cfcc7632f8d9f9ab83727c77a2fec063cb7b6e5eb23044ccf535ad49d46d394fb6f6bf6";
const GAMMA = "2903ba015a9abde26a5d081e84551e63be0fd4516e46ee6d593edeba46362455224bdc5d4327fcf8ed702e01de1c2f1657a253ba75e32a89c390142aaa28b30803c8b7cda6b2dedb7aeeaf5fda464ad17036bea1c4e6f7adbaed1ebe0335e0d81d92fff52a265017eeccb372e37d7a7bd431800eca28dfd82e21e8054114233f";
const DELTA = "228b515a17f28b89920873207477f8c7fc05582debaf3184febf1cfdedc5ce8812bb1156a9f6b360fcb2614e15d8a3ff07f2c699dc69ca830b20d2df91fe9cd32b15dc62a5c9e36597914ddbbfde48806a8eabe45c8d3cccf9578ad08e058f9202a4fd764f52470e2fcfff325fb9692f55d6b8b077eefeaa04e07152b4d1fa94";

// ── Case 1: n_public=0, proof.A=15*G1, proof.B=G2, proof.C=INF ──────────────

const CASE1_A = "2d96b121486ab9da7bf549e57d2f8a6cc1983a336903524fb05dcd507457f63c1dcb45731979ca35dfde49a476e273a1b1c9b52e3eca22fae279459920daa7e3";
const CASE1_B = "198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c21800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa";

// ── Case 2: n_public=1 (s=9), gamma_abc=[13*G1, 17*G1], proof.A=1177*G1 ─────

const CASE2_A    = "00e81ea8d81055564c708a31eda4cd0846a5dd383e847c41c0991fc9b00b728d24f716691c5aeeeb11a21cc308bb35583e4d15b43b84ad28d7130659d3190d9b";
const CASE2_B    = CASE1_B; // G2 generator
const CASE2_ABC0 = "05e86f8cc8a7a4f10f56093465679f17f8b8c3fdb41469e408b529e030f52f3f2857bd14bbc09767bed8e913d3ccb42b2bc8738f715417dd6f020725d22bcd90";
const CASE2_ABC1 = "1c6a451060210f3baad93fe1631753751da9857edae0468e8e4bee7dd33cfb2c2331a64aa86c50d2d1e0237893ef7744a77228881ce73fcc2ad555a37d4ab405";

// public input s=9 as [4]u64 LE
const PUB_S9: [4]u64 = .{ 9, 0, 0, 0 };

// tamper: proof.A shifted by +1*G1 (wrong A)
const TAMPER_A = "1ab3bceb293a5de9f4119d1c9bc9f7b7616d7c56e149cbf1cd480428a86593f319328a47c10de3ffef28450cd2fdfbbb5dfd32229d2f8303bdc594ce64efe0ff";

// ── Golden: Case 1 (no public inputs) ────────────────────────────────────────

test "golden case1: no public inputs — must verify" {
    var abc0 = [_]G1{G1.INFINITY};   // gamma_abc[0] = INF
    const vk = VerifyingKey{
        .alpha     = g1FromHex(ALPHA),
        .beta      = g2FromHex(BETA),
        .gamma     = g2FromHex(GAMMA),
        .delta     = g2FromHex(DELTA),
        .gamma_abc = &abc0,
    };
    const proof = Proof{
        .a = g1FromHex(CASE1_A),
        .b = g2FromHex(CASE1_B),
        .c = G1.INFINITY,
    };
    try std.testing.expect(groth16.verify(vk, proof, &[_][4]u64{}));
}

// ── Golden: Case 2 (one public input s=9) ────────────────────────────────────

test "golden case2: pub_input s=9 — must verify" {
    var abc = [_]G1{ g1FromHex(CASE2_ABC0), g1FromHex(CASE2_ABC1) };
    const vk = VerifyingKey{
        .alpha     = g1FromHex(ALPHA),
        .beta      = g2FromHex(BETA),
        .gamma     = g2FromHex(GAMMA),
        .delta     = g2FromHex(DELTA),
        .gamma_abc = &abc,
    };
    const proof = Proof{
        .a = g1FromHex(CASE2_A),
        .b = g2FromHex(CASE2_B),
        .c = G1.INFINITY,
    };
    try std.testing.expect(groth16.verify(vk, proof, &[_][4]u64{PUB_S9}));
}

// ── Tamper: wrong proof.A ─────────────────────────────────────────────────────

test "tamper: wrong proof.A — must reject" {
    var abc0 = [_]G1{G1.INFINITY};
    const vk = VerifyingKey{
        .alpha     = g1FromHex(ALPHA),
        .beta      = g2FromHex(BETA),
        .gamma     = g2FromHex(GAMMA),
        .delta     = g2FromHex(DELTA),
        .gamma_abc = &abc0,
    };
    const proof = Proof{
        .a = g1FromHex(TAMPER_A),  // A+1*G1 — invalid
        .b = g2FromHex(CASE1_B),
        .c = G1.INFINITY,
    };
    try std.testing.expect(!groth16.verify(vk, proof, &[_][4]u64{}));
}

test "tamper: wrong public input (s=10 instead of 9) — must reject" {
    var abc = [_]G1{ g1FromHex(CASE2_ABC0), g1FromHex(CASE2_ABC1) };
    const vk = VerifyingKey{
        .alpha     = g1FromHex(ALPHA),
        .beta      = g2FromHex(BETA),
        .gamma     = g2FromHex(GAMMA),
        .delta     = g2FromHex(DELTA),
        .gamma_abc = &abc,
    };
    const proof = Proof{
        .a = g1FromHex(CASE2_A),
        .b = g2FromHex(CASE2_B),
        .c = G1.INFINITY,
    };
    const pub_bad: [4]u64 = .{ 10, 0, 0, 0 };  // s=10, not 9
    try std.testing.expect(!groth16.verify(vk, proof, &[_][4]u64{pub_bad}));
}

test "tamper: swap proof.A and proof.C — must reject" {
    // Case1: A=15*G1, C=INF. Swap → A=INF, C=15*G1. Product breaks.
    var abc0 = [_]G1{G1.INFINITY};
    const vk = VerifyingKey{
        .alpha     = g1FromHex(ALPHA),
        .beta      = g2FromHex(BETA),
        .gamma     = g2FromHex(GAMMA),
        .delta     = g2FromHex(DELTA),
        .gamma_abc = &abc0,
    };
    const proof = Proof{
        .a = G1.INFINITY,
        .b = g2FromHex(CASE1_B),
        .c = g1FromHex(CASE1_A),   // A and C swapped
    };
    try std.testing.expect(!groth16.verify(vk, proof, &[_][4]u64{}));
}

test "tamper: wrong VK alpha — must reject" {
    // Use alpha=G1 instead of 3*G1 — breaks e(-alpha,beta)
    var abc0 = [_]G1{G1.INFINITY};
    const vk = VerifyingKey{
        .alpha     = G1.GENERATOR,  // wrong: should be 3*G1
        .beta      = g2FromHex(BETA),
        .gamma     = g2FromHex(GAMMA),
        .delta     = g2FromHex(DELTA),
        .gamma_abc = &abc0,
    };
    const proof = Proof{
        .a = g1FromHex(CASE1_A),
        .b = g2FromHex(CASE1_B),
        .c = G1.INFINITY,
    };
    try std.testing.expect(!groth16.verify(vk, proof, &[_][4]u64{}));
}

// ── Invariants ────────────────────────────────────────────────────────────────

test "invariant: double negation negG1(negG1(P)) affine roundtrip" {
    // Can't call negG1 directly (private), but verify uses it.
    // Instead: check that G1 addJac(P, neg(P)) == INFINITY for various scalars.
    const scalars: []const [4]u64 = &.{
        .{ 1, 0, 0, 0 },
        .{ 7, 0, 0, 0 },
        .{ 15, 0, 0, 0 },
        .{ 1177, 0, 0, 0 },
        .{ 0xdeadbeef, 0, 0, 0 },
    };
    for (scalars) |s| {
        const P  = G1.GENERATOR.scalarMul(s);
        const nP = G1.GENERATOR.scalarMul(s);
        // Build neg manually: negate Y in Jacobian
        const neg_P = G1{ .x = nP.x, .y = fp.neg(nP.y), .z = nP.z };
        const sum = P.addJac(neg_P);
        try std.testing.expect(sum.isInfinity());
    }
}

test "invariant: MSM linearity — msm([P,Q],[a+b]) == msm([P,Q],[a]) + msm([P,Q],[b])" {
    // msm with gamma_abc=[G1, G1]:
    //   msm(gamma_abc, [s]) = G1 + s*G1 = (1+s)*G1
    // Linearity: msm(s1+s2) == msm(s1) + msm(s2)
    // We test via verify: if we split a scalar into two addends across two calls.
    // Here we just test the scalar homogeneity via G1.scalarMul.
    const G = G1.GENERATOR;
    const pairs: []const struct { a: u64, b: u64 } = &.{
        .{ .a = 3,  .b = 5  },
        .{ .a = 11, .b = 17 },
        .{ .a = 0,  .b = 42 },
    };
    for (pairs) |p| {
        const sa: [4]u64 = .{ p.a, 0, 0, 0 };
        const sb: [4]u64 = .{ p.b, 0, 0, 0 };
        const sab: [4]u64 = .{ p.a + p.b, 0, 0, 0 };
        const Pa  = G.scalarMul(sa);
        const Pb  = G.scalarMul(sb);
        const Pab = G.scalarMul(sab);
        const sum = Pa.addJac(Pb);
        // Compare via affine bytes
        var got: [64]u8 = undefined;
        var exp: [64]u8 = undefined;
        sum.toAffineBytes(&got);
        Pab.toAffineBytes(&exp);
        try std.testing.expectEqualSlices(u8, &exp, &got);
    }
}

test "invariant: frFromBytes(0) == .{0,0,0,0}" {
    const buf = [_]u8{0} ** 32;
    const limbs = groth16.frFromBytes(&buf);
    try std.testing.expectEqual(limbs, [4]u64{ 0, 0, 0, 0 });
}

test "invariant: frFromBytes big-endian byte order" {
    // Byte 0 is most significant → limb[3]
    var buf = [_]u8{0} ** 32;
    buf[0] = 0x01;  // bit lands in limb[3], position 63
    const limbs = groth16.frFromBytes(&buf);
    try std.testing.expectEqual(limbs[3], 0x0100000000000000);
    try std.testing.expectEqual(limbs[0], 0);
}

// ── Stress: N random-scalar invalid proofs must all fail ─────────────────────

test "stress: 32 random-scalar proofs against case2 VK all reject" {
    // VK for case2. We make proofs with random A (different scalar each time).
    // None of them satisfies the pairing equation → all must return false.
    // We use a simple LCG to generate deterministic pseudo-random scalars.
    var abc = [_]G1{ g1FromHex(CASE2_ABC0), g1FromHex(CASE2_ABC1) };
    const vk = VerifyingKey{
        .alpha     = g1FromHex(ALPHA),
        .beta      = g2FromHex(BETA),
        .gamma     = g2FromHex(GAMMA),
        .delta     = g2FromHex(DELTA),
        .gamma_abc = &abc,
    };

    // LCG: x_{n+1} = (a*x_n + c) mod 2^64
    var rng: u64 = 0xdeadbeefcafe1234;
    const lcg_a: u64 = 6364136223846793005;
    const lcg_c: u64 = 1442695040888963407;

    var rejected: usize = 0;
    var i: usize = 0;
    while (i < 32) : (i += 1) {
        rng = lcg_a *% rng +% lcg_c;
        // Skip scalars that happen to equal the valid t=1177 (astronomically unlikely but safe)
        const scalar: u64 = rng | 1;  // force odd — valid t=1177 is odd too, but fine
        if (scalar == 1177) continue;

        const A_fake = G1.GENERATOR.scalarMul(.{ scalar, 0, 0, 0 });
        const proof = Proof{
            .a = A_fake,
            .b = g2FromHex(CASE2_B),
            .c = G1.INFINITY,
        };
        if (!groth16.verify(vk, proof, &[_][4]u64{PUB_S9})) {
            rejected += 1;
        }
    }
    try std.testing.expectEqual(rejected, 32);
}

test "stress: case2 rejects all 8 single-field tampers" {
    // Systematically tamper each component of the proof one at a time.
    var abc = [_]G1{ g1FromHex(CASE2_ABC0), g1FromHex(CASE2_ABC1) };
    const vk = VerifyingKey{
        .alpha     = g1FromHex(ALPHA),
        .beta      = g2FromHex(BETA),
        .gamma     = g2FromHex(GAMMA),
        .delta     = g2FromHex(DELTA),
        .gamma_abc = &abc,
    };

    const good_A = g1FromHex(CASE2_A);
    const good_B = g2FromHex(CASE2_B);
    const other  = G1.GENERATOR;  // any non-infinity G1

    // (tampered_A, tampered_C, pub_input, should_fail)
    const cases = [_]struct { a: G1, c: G1, inp: [4]u64, fail: bool }{
        // 1. Correct → must PASS (sanity)
        .{ .a = good_A, .c = G1.INFINITY, .inp = PUB_S9,          .fail = false },
        // 2. Wrong A
        .{ .a = other,  .c = G1.INFINITY, .inp = PUB_S9,          .fail = true  },
        // 3. Non-infinity C
        .{ .a = good_A, .c = other,       .inp = PUB_S9,          .fail = true  },
        // 4. Wrong pub input (s=0)
        .{ .a = good_A, .c = G1.INFINITY, .inp = .{0,0,0,0},      .fail = true  },
        // 5. Wrong pub input (s=1)
        .{ .a = good_A, .c = G1.INFINITY, .inp = .{1,0,0,0},      .fail = true  },
        // 6. Wrong pub input (s=8)
        .{ .a = good_A, .c = G1.INFINITY, .inp = .{8,0,0,0},      .fail = true  },
        // 7. Wrong pub input (s=10)
        .{ .a = good_A, .c = G1.INFINITY, .inp = .{10,0,0,0},     .fail = true  },
        // 8. A=INFINITY (degenerate)
        .{ .a = G1.INFINITY, .c = G1.INFINITY, .inp = PUB_S9,     .fail = true  },
    };

    for (cases, 0..) |tc, idx| {
        const proof = Proof{ .a = tc.a, .b = good_B, .c = tc.c };
        const result = groth16.verify(vk, proof, &[_][4]u64{tc.inp});
        if (tc.fail) {
            if (result) {
                std.debug.print("case {} should have failed but passed\n", .{idx});
            }
            try std.testing.expect(!result);
        } else {
            try std.testing.expect(result);
        }
    }
}
