// Smoke: drive the real mock-gateway with VERIFY_SIGS=1 using the
// webapp's keystore + dapp-actions modules. If sigs are wrong, this 401s.
//
//   bun test webapp_deploy/test/smoke-verify-sigs.test.js
//
// Boots sdk/ts/dev/mock-gateway.ts on an isolated port via child_process.

import { spawn } from "node:child_process";
import { test, expect, beforeAll, afterAll } from "bun:test";
import path from "node:path";
import { fileURLToPath } from "node:url";

if (typeof globalThis.localStorage === "undefined") {
  const store = new Map();
  globalThis.localStorage = {
    getItem: (k) => (store.has(k) ? store.get(k) : null),
    setItem: (k, v) => store.set(k, String(v)),
    removeItem: (k) => store.delete(k),
  };
}
if (typeof globalThis.window === "undefined") globalThis.window = globalThis;

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "../..");
const gatewayScript = path.join(repoRoot, "sdk/ts/dev/mock-gateway.ts");

// Bun's native fetch always exists; pin it now since other tests overwrite globalThis.fetch.
const realFetch = (typeof Bun !== "undefined" && Bun.fetch) ? Bun.fetch : globalThis.fetch.bind(globalThis);

const PORT = 18801;
let gw;

await import(path.join(repoRoot, "webapp_deploy/assets/src/lib/keystore.js"));
await import(path.join(repoRoot, "webapp_deploy/assets/src/lib/dapp-actions.js"));

globalThis.window.XB77_GATEWAY = `http://127.0.0.1:${PORT}`;

async function waitFor(url, tries = 50) {
  for (let i = 0; i < tries; i++) {
    try {
      const r = await fetch(url);
      if (r.ok) return true;
    } catch (_) {}
    await new Promise((r) => setTimeout(r, 100));
  }
  return false;
}

beforeAll(async () => {
  gw = spawn("bun", ["run", gatewayScript, "--port", String(PORT)], {
    env: { ...process.env, XB77_VERIFY_SIGS: "1" },
    stdio: ["ignore", "pipe", "pipe"],
  });
  gw.stdout.on("data", (b) => process.stdout.write("[gw] " + b));
  gw.stderr.on("data", (b) => process.stderr.write("[gw!] " + b));
  globalThis.fetch = realFetch; // undo any stubs from other test files
  const up = await waitFor(`http://127.0.0.1:${PORT}/_meta`);
  if (!up) throw new Error("mock-gateway did not come up on port " + PORT);
});

afterAll(() => {
  if (gw && !gw.killed) gw.kill("SIGTERM");
});

test("register_agent + submit_order succeed under VERIFY_SIGS=1", async () => {
  globalThis.XB77Keystore.lock();
  const k = await globalThis.XB77Keystore.generate("smoke-pw");

  // bootstrap: register
  const reg = await globalThis.XB77Actions.registerAgent(k.pubkeyHex, "merchant");
  expect(reg.agent_id).toMatch(/^ag_/);

  // signed: submit order — VERIFY_SIGS=1 will reject if canonical bytes wrong
  const r = await globalThis.XB77Actions.submitOrder({
    symbol: "SOL/USDC",
    side: "buy",
    amount: 100,
    price: 250,
    idempotency_key: "smoke-1",
  });
  expect(r).toBeDefined();
  expect(r.id || r.pipeline_id || r.order_id).toBeDefined();
});

test("query_pulse + claim_credits also pass sig verification", async () => {
  // session already generated by previous test? Bun runs tests in order in
  // a single file, so XB77Keystore session should still be set. Be safe:
  if (!globalThis.XB77Keystore.currentPubkey()) {
    await globalThis.XB77Keystore.generate("smoke-pw-2");
    await globalThis.XB77Actions.registerAgent(globalThis.XB77Keystore.currentPubkey(), "merchant");
  }
  const pulse = await globalThis.XB77Actions.queryPulse();
  expect(pulse).toBeDefined();

  // claim_credits with a dummy tx — the mock accepts any proof_tx string.
  const claim = await globalThis.XB77Actions.claimCredits("tx_smoke_abc123");
  expect(claim).toBeDefined();
});
