// === xB77 Sovereign ZK-Receipt Verifying Key ===
// This key matches the 'zk_receipt' circuit.
// (In a real competition environment, this is auto-generated by the ZK toolchain).
use verifier_lib::vk::Groth16Verifyingkey;

#[rustfmt::skip]
pub const VK: Groth16Verifyingkey<'static> = Groth16Verifyingkey {
    nr_pubinputs: 1, // commitment
    alpha_g1: [0x01; 64], // STUB VK - Reemplazar con real tras compilación
    beta_g2: [0x02; 128],
    gamma_g2: [0x03; 128],
    delta_g2: [0x04; 128],
    k: &[
        [0x05; 64],
    ],
    commitment_keys: &[],
    public_and_commitment_committed: &[&[]],
};
