#!/usr/bin/env bash
# scripts/evm-local.sh — start anvil + deploy xB77 EVM contracts for local testing.
#
# Usage:
#   scripts/evm-local.sh              # start anvil, deploy, write .anvil-addresses
#   scripts/evm-local.sh --stop       # kill the anvil instance started by this script
#   scripts/evm-local.sh --status     # print current .anvil-addresses if available
#
# After running, source the addresses into your env:
#   source .anvil-addresses
#   bun test sdk/ts/test/e2e-arbitrum.test.ts
#
# Or run the full e2e suite in one shot:
#   scripts/evm-local.sh && source .anvil-addresses && bun test sdk/ts/test/e2e-arbitrum.test.ts

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EVM_DIR="${REPO}/onchain/evm"
ADDR_FILE="${REPO}/.anvil-addresses"
PID_FILE="/tmp/xb77-anvil.pid"

ANVIL_PORT="${ANVIL_PORT:-8545}"
RPC="http://127.0.0.1:${ANVIL_PORT}"
# anvil well-known account 0 private key
DEPLOYER_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

GRN=$'\033[0;32m'; YLW=$'\033[0;33m'; RED=$'\033[0;31m'; RST=$'\033[0m'; BLD=$'\033[1m'
ok()   { printf "  ${GRN}✔${RST} %s\n" "$*"; }
warn() { printf "  ${YLW}⚠${RST} %s\n" "$*"; }
fail() { printf "  ${RED}✘${RST} %s\n" "$*" >&2; exit 1; }
step() { printf "\n${BLD}▶ %s${RST}\n" "$*"; }

anvil_healthy() {
    curl -fsS -X POST "${RPC}" \
        -H 'Content-Type: application/json' \
        -d '{"jsonrpc":"2.0","id":1,"method":"eth_blockNumber","params":[]}' \
        >/dev/null 2>&1
}

# ── --stop ────────────────────────────────────────────────────────────────────
if [[ "${1:-}" == "--stop" ]]; then
    if [[ -f "${PID_FILE}" ]]; then
        PID=$(cat "${PID_FILE}")
        kill "${PID}" 2>/dev/null && ok "anvil (PID ${PID}) stopped" || warn "anvil already gone"
        rm -f "${PID_FILE}"
    else
        warn "no PID file at ${PID_FILE} — nothing to stop"
    fi
    rm -f "${ADDR_FILE}"
    exit 0
fi

# ── --status ──────────────────────────────────────────────────────────────────
if [[ "${1:-}" == "--status" ]]; then
    if anvil_healthy; then
        ok "anvil is running on ${RPC}"
    else
        warn "anvil is NOT running on ${RPC}"
    fi
    if [[ -f "${ADDR_FILE}" ]]; then
        echo ""
        cat "${ADDR_FILE}"
    fi
    exit 0
fi

# ── start anvil ───────────────────────────────────────────────────────────────
step "Anvil"
if anvil_healthy; then
    ok "already running on :${ANVIL_PORT} — reusing"
else
    anvil \
        --port "${ANVIL_PORT}" \
        --block-time 1 \
        --chain-id 31337 \
        --silent \
        >/tmp/xb77-anvil.log 2>&1 &
    echo $! > "${PID_FILE}"
    ok "started (PID $(cat "${PID_FILE}"))"

    printf "  waiting for RPC"
    for i in $(seq 1 40); do
        if anvil_healthy; then printf " ready\n"; break; fi
        printf "."
        sleep 0.25
        if [[ $i -eq 40 ]]; then
            printf "\n"
            tail -20 /tmp/xb77-anvil.log >&2
            fail "anvil did not come up after 10s"
        fi
    done
fi

# ── deploy contracts ──────────────────────────────────────────────────────────
step "Deploy contracts"
cd "${EVM_DIR}"

DEPLOY_OUT=$(forge script script/DeployLocal.s.sol:DeployLocal \
    --rpc-url "${RPC}" \
    --private-key "${DEPLOYER_KEY}" \
    --broadcast \
    2>&1)

# Extract KEY=value lines from forge console.log output
CONSTITUTION=$(echo "${DEPLOY_OUT}" | grep "CONSTITUTION_ADDRESS="   | tail -1 | cut -d= -f2 | tr -d ' \r')
POLICY=$(echo "${DEPLOY_OUT}"       | grep "SOVEREIGN_POLICY_ADDRESS=" | tail -1 | cut -d= -f2 | tr -d ' \r')
ENFORCER=$(echo "${DEPLOY_OUT}"     | grep "CAVEAT_ENFORCER_ADDRESS="  | tail -1 | cut -d= -f2 | tr -d ' \r')
SETTLEMENT=$(echo "${DEPLOY_OUT}"   | grep "SETTLEMENT_ADDRESS="       | tail -1 | cut -d= -f2 | tr -d ' \r')

if [[ -z "${CONSTITUTION}" || -z "${POLICY}" ]]; then
    echo "${DEPLOY_OUT}" >&2
    fail "could not parse deployed addresses from forge output"
fi

ok "MockStylusConstitution → ${CONSTITUTION}"
ok "SovereignPolicy        → ${POLICY}"
ok "SovereignCaveatEnforcer→ ${ENFORCER}"
ok "Settlement             → ${SETTLEMENT}"

# ── write address file ────────────────────────────────────────────────────────
step "Writing ${ADDR_FILE}"
cat >"${ADDR_FILE}" <<EOF
# xB77 EVM local deployment — generated by scripts/evm-local.sh
# Source this file before running SDK e2e tests:
#   source .anvil-addresses && bun test sdk/ts/test/e2e-arbitrum.test.ts

export ANVIL_URL="${RPC}"
export CONSTITUTION_ADDRESS="${CONSTITUTION}"
export SOVEREIGN_POLICY_ADDRESS="${POLICY}"
export CAVEAT_ENFORCER_ADDRESS="${ENFORCER}"
export SETTLEMENT_ADDRESS="${SETTLEMENT}"
EOF
ok "written"

# ── summary ───────────────────────────────────────────────────────────────────
printf "\n${BLD}Stack ready.${RST}\n"
printf "  Run SDK e2e tests:\n"
printf "    source .anvil-addresses\n"
printf "    bun test sdk/ts/test/e2e-arbitrum.test.ts\n"
printf "  Or in one shot:\n"
printf "    scripts/evm-local.sh && source .anvil-addresses && bun test sdk/ts/test/e2e-arbitrum.test.ts\n"
printf "  Stop anvil:\n"
printf "    scripts/evm-local.sh --stop\n\n"
