FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    bash \
    ca-certificates \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

# Configure git to use https always and no prompt
RUN git config --global url."https://github.com/".insteadOf git@github.com:
RUN git config --global url."https://".insteadOf git://

# Install Solana CLI (Arcium docs reference Solana tooling)
RUN curl --proto '=https' --tlsv1.2 -sSfL https://solana-install.solana.workers.dev | bash

ENV PATH="/root/.local/share/solana/install/active_release/bin:$PATH"

WORKDIR /work

ENTRYPOINT ["solana"]
