services:
  light-devcontainer:
    build:
      context: .
      dockerfile: Containerfile
    image: xb77-light-devcontainer:local
    container_name: light-devcontainer
    network_mode: "host"
    user: "node"
    working_dir: /work
    environment:
      - LIGHT_PROTOCOL_PROGRAMS_DIR=/work/cli/bin
    volumes:
      - ${LIGHT_REPO}:/work
      - lightprotocol-solana-config:/home/node/.config/solana
    command: ["tail", "-f", "/dev/null"]

volumes:
  lightprotocol-solana-config:
