services:
  light-devcontainer:
    build:
      context: .
      dockerfile: Containerfile
    image: xb77-light-devcontainer:local
    container_name: light-devcontainer
    network_mode: "host"
    working_dir: /app
    environment:
      - LIGHT_PROTOCOL_PROGRAMS_DIR=/app/cli/bin
    volumes:
      - ${LIGHT_REPO}:/app
      - lightprotocol-solana-config:/root/.config/solana
    command: ["tail", "-f", "/dev/null"]

volumes:
  lightprotocol-solana-config:
